name: "drupal"
type: "php:8.0"
build:
  flavor: composer

dependencies:
  php:
    "drush/drush": "^9.0"
    composer/composer: "^2"

runtime:
  extensions:
    - redis
    - newrelic

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: db:mysql
  redis: cache:redis

# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    "/":
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: "web"
      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m
      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: "/index.php"
      # Deny access to static files in this location.
      allow: false
      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
    "/sites/default/files":
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: "/index.php"
      root: "web/sites/default/files"
      # Do not execute PHP scripts.
      scripts: false

# The size of the persistent disk of the application (in MB).
disk: 2048
# The 'mounts' describe writable, persistent filesystem mounts in the application. The keys are
# directory paths, relative to the application root. The values are strings such as
# 'shared:files/NAME', where NAME is just a unique name for the mount.
mounts:
  "/web/sites/default/files": "shared:files/files"
  "/tmp": "shared:files/tmp"
  "/private": "shared:files/private"
  "/translations": "shared:files/translations"
  "/drush-backups": "shared:files/drush-backups"

hooks:
  build: |
    # Expand PATH for composer binaries
    export PATH=/app/vendor/bin:$PATH
  deploy: |
    # This loops trough all aliases and runs command.
    cd web
    drush updatedb --no-cache-clear -y
    drush cr -y
    drush cim -y
    drush cr -y
    drush deploy:hook -y
