"https://cms.drupal-react-talk.{default}/": &drupal
  type: upstream
  upstream: "drupal:http"
  tls:
    strict_transport_security:
      enabled: true
  cache:
    enabled: true
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ["/^SS?ESS/", "/^Drupal.visitor/"]
